=== permguard/permguard/pkg/accesscontrol/policies/data/ac-policy-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Syntax": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Type": {
      "type": "string"
    },
    "Permit": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    },
    "Forbid": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    }
  },
  "required": [
    "Syntax",
    "Type",
    "Permit",
    "Forbid"
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/build-virtual-state/with-conditions/permguard1/case4/input-policy-2.json
{
  "Syntax": "permguard1",
  "Type": "AC",
  "Name": "empty",
  "Permit": [
    {
      "Name": "permit-hr/person/delete/any",
      "Actions": [
        "person:DeleteEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/giovanni.bianchi",
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ],
      "Condition": "DateGreaterThan({{.PermGuard.TokenIssueTime}})'"
    }
  ],
  "Forbid": []
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/register-policy/notvalid/without-conditions/permguard1/case1/input-policy-4.json
{
  "Syntax": "permguard1",
  "Name": "person-base-reader",
  "Type": "AC",
  "Permit": [
      {
          "Name": "permit-hr:person:reader:any",
          "Actions": [
              "person:ListEmployee",
              "person:ReadEmployee"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:organisation:person/*"
          ]
      },
      {
          "Name": "permit-hr:timesheet:writer:any",
          "Actions": [
              "person:ReadTimesheet",
              "person:CreateTimesheet",
              "person:UpdateTimesheet",
              "person:DeleteTimesheet"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:time-management:person/*"
          ]
      }
  ],
  "Forbid": [
    {
        "Name": "Invalid Name",
        "Actions": [
            "person:ReadEmployee"
        ],
        "Resources": [
            "uur:581616507495:default:hr-app:organisation:person/johon"
        ]
    }
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/build-virtual-state/with-conditions/permguard1/case8/input-policy-1.json
{
  "Syntax": "permguard1",
  "Type": "AC",
  "Name": "person-base-reader",
  "Permit": [],
  "Forbid": [
    {
      "Name": "forbid-hr/person/writer/any",
      "Actions": [
        "person:ReadEmployee",
        "person:WriteEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    }
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/build-virtual-state/without-conditions/permguard1/case6/input-policy-1.json
{
  "Syntax": "permguard1",
  "Type": "AC",
  "Name": "person-base-reader",
  "Permit": [
    {
      "Name": "permit-hr/person/reader/any1",
      "Actions": [
        "person:ListEmployee",
        "person:ReadEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/nicola.gallo",
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    },
    {
      "Name": "permit-hr/person/reader/any1",
      "Actions": [
        "person:ReadEmployee",
        "person:WriteEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    }
  ],
  "Forbid": [
    {
      "Name": "forbid-hr/person/reader/any1",
      "Actions": [
        "person:ListEmployee",
        "person:ReadEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/nicola.gallo",
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    },
    {
      "Name": "forbid-hr/person/reader/any1",
      "Actions": [
        "person:ReadEmployee",
        "person:WriteEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    }
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/register-policy/valid/without-conditions/permguard1/case1/input-policy-3.json
{
    "Syntax": "permguard1",
    "Name": "person-base-reader",
    "Type": "AC",
    "Permit": [],
    "Forbid": [
      {
          "Name": "forbid-hr/person/reader/johon",
          "Actions": [
              "person:ReadEmployee"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:organisation:person/johon"
          ]
      }
    ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/register-policy/notvalid/without-conditions/permguard1/case1/input-policy-2.json
{
  "Syntax": "permguard1",
  "Name": "person-base-reader",
  "Type": "AC",
  "Permit": [
      {
          "Name": "Invalid name",
          "Actions": [
              "person:ListEmployee",
              "person:ReadEmployee"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:organisation:person/*"
          ]
      },
      {
          "Name": "permit-hr:timesheet:writer:any",
          "Actions": [
              "person:ReadTimesheet",
              "person:CreateTimesheet",
              "person:UpdateTimesheet",
              "person:DeleteTimesheet"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:time-management:person/*"
          ]
      }
  ],
  "Forbid": [
    {
        "Name": "forbid-hr/person/reader/johon",
        "Actions": [
            "person:ReadEmployee"
        ],
        "Resources": [
            "uur:581616507495:default:hr-app:organisation:person/johon"
        ]
    }
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-states/create-state/permguard1/case4/input-policy-1.json
{
    "Syntax": "permguard1",
    "Type": "AC",
    "Name": "person-base-reader",
    "Permit": [
        {
            "Name": "permit-hr:person:reader:any",
            "Actions": [
                "person:ListEmployee",
                "person:ReadEmployee"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:organisation:person/*"
            ]
        },
        {
          "Name": "permit-hr:person:reader:any",
          "Actions": [
              "person:ListEmployee",
              "person:ReadEmployee"
          ],
          "Resources": [
              "uur:581616507495:default:hr-app:organisation:person/*"
          ]
      }
    ],
    "Forbid": []
}

=== permguard/permguard/pkg/extensions/files/testdata/extensions/files/validate-jsonschema/valid/permguard1/case1/input-policy-4.json
{
    "Syntax": "permguard1",
    "Name": "person-base-reader",
    "Type": "AC",
    "Permit": [
        {
            "Actions": [
                "person:ListEmployee",
                "person:ReadEmployee"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:organisation:person/*"
            ]
        },
        {
            "Actions": [
                "person:ReadTimesheet",
                "person:CreateTimesheet",
                "person:UpdateTimesheet",
                "person:DeleteTimesheet"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:time-management:person/*"
            ]
        }
    ],
    "Forbid": []
}
