=== permguard/permguard/pkg/accesscontrol/policies/data/ac-policy-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Syntax": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Type": {
      "type": "string"
    },
    "Permit": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    },
    "Forbid": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    }
  },
  "required": [
    "Syntax",
    "Type",
    "Permit",
    "Forbid"
  ]
}

=== permguard/permguard/pkg/accesscontrol/permissions/testdata/permissions-engine/build-virtual-state/without-conditions/permguard1/case4/input-policy-1.json
{
  "Syntax": "permguard1",
  "Type": "AC",
  "Name": "person-base-reader",
  "Permit": [],
  "Forbid": [
    {
      "Name": "forbid-hr/person/reader/any",
      "Actions": [
        "person:ListEmployee",
        "person:ReadEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/nicola.gallo",
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    },
    {
      "Name": "forbid-hr/person/reader/any",
      "Actions": [
        "person:ReadEmployee",
        "person:WriteEmployee"
      ],
      "Resources": [
        "uur:581616507495:default:hr-app:organisation:person/irene.banchi"
      ]
    }
  ]
}
